[settings]
idiomatic_version_file_enable_tools = ["dotnet", "elixir", "go", "haskell", "java", "javascript", "kotlin", "node", "python", "ruby", "rust", "scala"]
[tools]
java = "openjdk-25"
node = "22.11.0"
